### ISSUE TITLE
 Cannot call method 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by jaganathanb** [arvindr21/slush-wean#1]
I am getting the following error when run the slush wean.

...appdata\roaming\npm\node_modules\slush-wean\slushfile.js:2
0
  var username = string.toLowerCase();
                        ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at format (...appdata\roaming\npm\node_modules\slush-wean
\slushfile.js:20:25)
    at ....appdata\roaming\npm\node_modules\slush-wean\slushfi
le.js:35:15
    at Object.<anonymous> (...\appdata\roaming\npm\node_module
s\slush-wean\slushfile.js:38:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Liftoff.handleArguments (....\AppData\Roaming\npm\node_m
odules\slush\bin\slush.js:90:3)

**Comment by GoGaetan** [comment]
cmd:
gaetang:scotch-chat serge$ slush wean

result:
/usr/local/lib/node_modules/slush-wean/slushfile.js:35
    userName: format(user.name) || osUserName,
                         ^

TypeError: Cannot read property 'name' of undefined
    at /usr/local/lib/node_modules/slush-wean/slushfile.js:35:26
    at Object.<anonymous> (/usr/local/lib/node_modules/slush-wean/slushfile.js:38:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/slush/bin/slush.js:90:3)
    at Liftoff.launch (/usr/local/lib/node_modules/slush/node_modules/liftoff/index.js:153:6)

slush version: [slush] 1.1.1
npm version : 3.10.5
Os : Mac Os X Yosemite

Need some help.
